/**
 * The example catalog: the single source of metadata for every example, plus a
 * lazy loader for its module. `pnpm examples:list`, `pnpm example -- <name>`,
 * `--help`, and `pnpm examples:check` all read this. Keeping metadata here (not
 * in each file) lets the example files stay minimal — just constants + body — and
 * lets `list` render without importing every example's (sometimes heavy) deps.
 *
 * Each entry's `name` must equal the loaded module's `default.name` (the check
 * enforces this), and each module's default export is the runnable `Example`.
 */
import type { Example, ExampleMeta } from "./shared/harness.js";

export interface RegistryEntry extends ExampleMeta {
  load: () => Promise<{ default: Example }>;
}

export const registry: RegistryEntry[] = [
  { name: "neutral:bundle-status", file: "examples/src/neutral/bundle-status.ts", group: "neutral", role: "none", network: "rpc-read", summary: "Read Neutral pending requests, available tokens and accounting state.", transactional: false, offline: false, load: () => import("./neutral/bundle-status.js") },
  {
    name: "neutral:bundle-register-depositor", file: "examples/src/neutral/bundle-register-depositor.ts",
    group: "neutral", role: "manager", network: "rpc-read",
    summary: "Neutral bundle register-depositor; uses live bundle state.", transactional: true, offline: false,
    load: () => import("./neutral/bundle-register-depositor.js"),
  },
  {
    name: "neutral:bundle-claim", file: "examples/src/neutral/bundle-claim.ts",
    group: "neutral", role: "manager", network: "rpc-read",
    summary: "Neutral bundle claim; uses live bundle state.", transactional: true, offline: false,
    load: () => import("./neutral/bundle-claim.js"),
  },
  {
    name: "neutral:bundle-request-withdraw", file: "examples/src/neutral/bundle-request-withdraw.ts",
    group: "neutral", role: "manager", network: "rpc-read",
    summary: "Neutral bundle request-withdraw; uses live bundle state.", transactional: true, offline: false,
    load: () => import("./neutral/bundle-request-withdraw.js"),
  },
  {
    name: "neutral:bundle-refresh", file: "examples/src/neutral/bundle-refresh.ts",
    group: "neutral", role: "manager", network: "rpc-read",
    summary: "Neutral bundle refresh; uses live bundle state.", transactional: true, offline: false,
    load: () => import("./neutral/bundle-refresh.js"),
  },
  {
    name: "neutral:bundle-deposit", file: "examples/src/neutral/bundle-deposit.ts",
    group: "neutral", role: "manager", network: "rpc-read",
    summary: "Neutral bundle deposit; uses live bundle state.", transactional: true, offline: false,
    load: () => import("./neutral/bundle-deposit.js"),
  },
  {
    name: "neutral:bundle-init", file: "examples/src/neutral/bundle-init.ts",
    group: "neutral", role: "manager", network: "rpc-read",
    summary: "Neutral bundle init; uses live bundle state.", transactional: true, offline: false,
    load: () => import("./neutral/bundle-init.js"),
  },
  // Vault / core
  {
    name: "vault:initialize",
    file: "examples/src/vault/initialize.ts",
    group: "vault",
    role: "admin",
    network: "none",
    summary: "Initialize a vault and inspect the generated operation.",
    transactional: true,
    offline: true,
    load: () => import("./vault/initialize.js"),
  },
  {
    name: "vault:deposit",
    file: "examples/src/vault/deposit.ts",
    group: "vault",
    role: "user",
    network: "none",
    summary: "Deposit the profile asset into the vault.",
    transactional: true,
    offline: true,
    load: () => import("./vault/deposit.js"),
  },
  {
    name: "vault:request-withdraw",
    file: "examples/src/vault/request-withdraw.ts",
    group: "vault",
    role: "user",
    network: "none",
    summary: "Request a withdrawal from the vault.",
    transactional: true,
    offline: true,
    load: () => import("./vault/request-withdraw.js"),
  },
  {
    name: "vault:withdraw",
    file: "examples/src/vault/withdraw.ts",
    group: "vault",
    role: "user",
    network: "none",
    summary: "Claim a previously requested withdrawal.",
    transactional: true,
    offline: true,
    load: () => import("./vault/withdraw.js"),
  },
  {
    name: "vault:instant-withdraw",
    file: "examples/src/vault/instant-withdraw.ts",
    group: "vault",
    role: "user",
    network: "none",
    summary: "Withdraw immediately against idle vault assets.",
    transactional: true,
    offline: true,
    load: () => import("./vault/instant-withdraw.js"),
  },
  {
    name: "vault:cancel-request-withdraw",
    file: "examples/src/vault/cancel-request-withdraw.ts",
    group: "vault",
    role: "user",
    network: "none",
    summary: "Cancel an outstanding withdrawal request.",
    transactional: true,
    offline: true,
    load: () => import("./vault/cancel-request-withdraw.js"),
  },
  {
    name: "vault:query-position",
    file: "examples/src/vault/query-position.ts",
    group: "vault",
    role: "none",
    network: "rpc-read",
    summary: "Read a user's vault position (read-only).",
    transactional: false,
    offline: false,
    load: () => import("./vault/query-position.js"),
  },
  {
    name: "vault:query-strategy-positions",
    file: "examples/src/vault/query-strategy-positions.ts",
    group: "vault",
    role: "none",
    network: "rpc-read",
    summary: "Read the vault's per-strategy allocation (read-only).",
    transactional: false,
    offline: false,
    load: () => import("./vault/query-strategy-positions.js"),
  },
  {
    name: "vault:initialize-with-metadata",
    file: "examples/src/vault/initialize-with-metadata.ts",
    group: "vault",
    role: "admin",
    network: "none",
    summary: "Initialize a vault with LP token metadata.",
    transactional: true,
    offline: true,
    load: () => import("./vault/initialize-with-metadata.js"),
  },
  {
    name: "vault:set-token-metadata",
    file: "examples/src/vault/set-token-metadata.ts",
    group: "vault",
    role: "admin",
    network: "none",
    summary: "Create LP token metadata for an initialized vault.",
    transactional: true,
    offline: true,
    load: () => import("./vault/set-token-metadata.js"),
  },
  {
    name: "vault:update-config",
    file: "examples/src/vault/update-config.ts",
    group: "vault",
    role: "admin",
    network: "none",
    summary: "Update one vault configuration field.",
    transactional: true,
    offline: true,
    load: () => import("./vault/update-config.js"),
  },
  {
    name: "vault:accept-admin",
    file: "examples/src/vault/accept-admin.ts",
    group: "vault",
    role: "admin",
    network: "none",
    summary: "Accept the pending-admin role for a vault.",
    transactional: true,
    offline: true,
    load: () => import("./vault/accept-admin.js"),
  },
  {
    name: "vault:harvest-fee",
    file: "examples/src/vault/harvest-fee.ts",
    group: "vault",
    role: "admin",
    network: "none",
    summary: "Harvest accrued vault fees into LP token accounts.",
    transactional: true,
    offline: true,
    load: () => import("./vault/harvest-fee.js"),
  },
  {
    name: "vault:add-adaptor",
    file: "examples/src/vault/add-adaptor.ts",
    group: "vault",
    role: "admin",
    network: "none",
    summary: "Register an adaptor program on a vault.",
    transactional: true,
    offline: true,
    load: () => import("./vault/add-adaptor.js"),
  },
  {
    name: "vault:remove-adaptor",
    file: "examples/src/vault/remove-adaptor.ts",
    group: "vault",
    role: "admin",
    network: "none",
    summary: "Deregister an adaptor program from a vault.",
    transactional: true,
    offline: true,
    load: () => import("./vault/remove-adaptor.js"),
  },
  {
    name: "vault:update-adaptor-policy",
    file: "examples/src/vault/update-adaptor-policy.ts",
    group: "vault",
    role: "admin",
    network: "none",
    summary: "Update a vault's adaptor policy as protocol admin.",
    transactional: true,
    offline: true,
    load: () => import("./vault/update-adaptor-policy.js"),
  },

  // Protocol
  {
    name: "protocol:update-treasury",
    file: "examples/src/protocol/update-treasury.ts",
    group: "protocol",
    role: "admin",
    network: "none",
    summary: "Update the protocol treasury address.",
    transactional: true,
    offline: true,
    load: () => import("./protocol/update-treasury.js"),
  },
  {
    name: "protocol:set-pending-admin",
    file: "examples/src/protocol/set-pending-admin.ts",
    group: "protocol",
    role: "admin",
    network: "none",
    summary: "Set the incoming protocol admin.",
    transactional: true,
    offline: true,
    load: () => import("./protocol/set-pending-admin.js"),
  },
  {
    name: "protocol:accept-admin",
    file: "examples/src/protocol/accept-admin.ts",
    group: "protocol",
    role: "admin",
    network: "none",
    summary: "Accept the pending protocol-admin role.",
    transactional: true,
    offline: true,
    load: () => import("./protocol/accept-admin.js"),
  },

  // Kamino
  {
    name: "kamino:market-init",
    file: "examples/src/kamino/market-init.ts",
    group: "kamino",
    role: "manager",
    network: "rpc-read",
    summary: "Initialize a Kamino lending-market strategy.",
    transactional: true,
    offline: false,
    load: () => import("./kamino/market-init.js"),
  },
  {
    name: "kamino:market-deposit",
    file: "examples/src/kamino/market-deposit.ts",
    group: "kamino",
    role: "manager",
    network: "rpc-read",
    summary: "Deposit vault assets into a Kamino lending market.",
    transactional: true,
    offline: false,
    load: () => import("./kamino/market-deposit.js"),
  },
  {
    name: "kamino:market-withdraw",
    file: "examples/src/kamino/market-withdraw.ts",
    group: "kamino",
    role: "manager",
    network: "rpc-read",
    summary: "Withdraw vault assets from a Kamino lending market.",
    transactional: true,
    offline: false,
    load: () => import("./kamino/market-withdraw.js"),
  },
  {
    name: "kamino:market-claim-reward",
    file: "examples/src/kamino/market-claim-reward.ts",
    group: "kamino",
    role: "manager",
    network: "rpc-and-http",
    summary: "Claim a Kamino market farm reward (optional Jupiter swap).",
    transactional: true,
    offline: false,
    load: () => import("./kamino/market-claim-reward.js"),
  },
  {
    name: "kamino:kvault-init",
    file: "examples/src/kamino/kvault-init.ts",
    group: "kamino",
    role: "manager",
    network: "none",
    summary: "Initialize a Kamino vault (kvault) strategy.",
    transactional: true,
    offline: true,
    load: () => import("./kamino/kvault-init.js"),
  },
  {
    name: "kamino:kvault-deposit",
    file: "examples/src/kamino/kvault-deposit.ts",
    group: "kamino",
    role: "manager",
    network: "rpc-read",
    summary: "Deposit vault assets into a Kamino vault (kvault).",
    transactional: true,
    offline: false,
    load: () => import("./kamino/kvault-deposit.js"),
  },
  {
    name: "kamino:kvault-withdraw",
    file: "examples/src/kamino/kvault-withdraw.ts",
    group: "kamino",
    role: "manager",
    network: "rpc-read",
    summary: "Withdraw vault assets from a Kamino vault (kvault).",
    transactional: true,
    offline: false,
    load: () => import("./kamino/kvault-withdraw.js"),
  },
  {
    name: "kamino:kvault-claim-reward",
    file: "examples/src/kamino/kvault-claim-reward.ts",
    group: "kamino",
    role: "manager",
    network: "rpc-and-http",
    summary: "Claim a Kamino vault farm reward (optional Jupiter swap).",
    transactional: true,
    offline: false,
    load: () => import("./kamino/kvault-claim-reward.js"),
  },
  {
    name: "kamino:kvault-direct-withdraw",
    file: "examples/src/kamino/kvault-direct-withdraw.ts",
    group: "kamino",
    role: "user",
    network: "rpc-read",
    summary: "User direct-withdraw from a Kamino vault (kvault).",
    transactional: true,
    offline: false,
    load: () => import("./kamino/kvault-direct-withdraw.js"),
  },
  {
    name: "kamino:kvault-request-and-direct-withdraw",
    file: "examples/src/kamino/kvault-request-and-direct-withdraw.ts",
    group: "kamino",
    role: "user",
    network: "rpc-read",
    summary: "Request + direct-withdraw from a Kamino vault in one tx.",
    transactional: true,
    offline: false,
    load: () => import("./kamino/kvault-request-and-direct-withdraw.js"),
  },
  {
    name: "kamino:kvault-init-direct-withdraw",
    file: "examples/src/kamino/kvault-init-direct-withdraw.ts",
    group: "kamino",
    role: "admin",
    network: "none",
    summary: "Register a Kamino vault as a direct-withdraw strategy.",
    transactional: true,
    offline: true,
    load: () => import("./kamino/kvault-init-direct-withdraw.js"),
  },

  // Spot
  {
    name: "spot:swap-init",
    file: "examples/src/spot/swap-init.ts",
    group: "spot",
    role: "manager",
    network: "none",
    summary: "Initialize a Spot swap strategy.",
    transactional: true,
    offline: true,
    load: () => import("./spot/swap-init.js"),
  },
  {
    name: "spot:swap-buy",
    file: "examples/src/spot/swap-buy.ts",
    group: "spot",
    role: "manager",
    network: "rpc-and-http",
    summary: "Buy the foreign asset via a Jupiter spot swap.",
    transactional: true,
    offline: false,
    load: () => import("./spot/swap-buy.js"),
  },
  {
    name: "spot:swap-sell",
    file: "examples/src/spot/swap-sell.ts",
    group: "spot",
    role: "manager",
    network: "rpc-and-http",
    summary: "Sell the foreign asset via a Jupiter spot swap.",
    transactional: true,
    offline: false,
    load: () => import("./spot/swap-sell.js"),
  },
  {
    name: "spot:earn-init",
    file: "examples/src/spot/earn-init.ts",
    group: "spot",
    role: "manager",
    network: "none",
    summary: "Initialize the Jupiter Earn strategy.",
    transactional: true,
    offline: true,
    load: () => import("./spot/earn-init.js"),
  },
  {
    name: "spot:earn-deposit",
    file: "examples/src/spot/earn-deposit.ts",
    group: "spot",
    role: "manager",
    network: "none",
    summary: "Deposit the vault asset into Jupiter Earn.",
    transactional: true,
    offline: true,
    load: () => import("./spot/earn-deposit.js"),
  },
  {
    name: "spot:earn-withdraw",
    file: "examples/src/spot/earn-withdraw.ts",
    group: "spot",
    role: "manager",
    network: "none",
    summary: "Withdraw the vault asset from Jupiter Earn.",
    transactional: true,
    offline: true,
    load: () => import("./spot/earn-withdraw.js"),
  },
  {
    name: "spot:earn-extend-lut",
    file: "examples/src/spot/earn-extend-lut.ts",
    group: "spot",
    role: "manager",
    network: "rpc-read",
    summary: "Pre-load the lookup table with Jupiter Earn accounts.",
    transactional: true,
    offline: false,
    load: () => import("./spot/earn-extend-lut.js"),
  },
  {
    name: "spot:earn-init-direct-withdraw",
    file: "examples/src/spot/earn-init-direct-withdraw.ts",
    group: "spot",
    role: "admin",
    network: "none",
    summary: "Register Jupiter Earn as a vault direct-withdraw strategy.",
    transactional: true,
    offline: true,
    load: () => import("./spot/earn-init-direct-withdraw.js"),
  },
  {
    name: "spot:query-strategy-positions",
    file: "examples/src/spot/query-strategy-positions.ts",
    group: "spot",
    role: "none",
    network: "rpc-read",
    summary: "Read the vault's Spot/Earn strategy positions (read-only).",
    transactional: false,
    offline: false,
    load: () => import("./spot/query-strategy-positions.js"),
  },

  // Trustful
  {
    name: "trustful:arbitrary-init",
    file: "examples/src/trustful/arbitrary-init.ts",
    group: "trustful",
    role: "manager",
    network: "none",
    summary: "Initialize a Trustful arbitrary strategy.",
    transactional: true,
    offline: true,
    load: () => import("./trustful/arbitrary-init.js"),
  },
  {
    name: "trustful:arbitrary-deposit",
    file: "examples/src/trustful/arbitrary-deposit.ts",
    group: "trustful",
    role: "manager",
    network: "none",
    summary: "Deposit into a Trustful arbitrary strategy.",
    transactional: true,
    offline: true,
    load: () => import("./trustful/arbitrary-deposit.js"),
  },
  {
    name: "trustful:arbitrary-withdraw",
    file: "examples/src/trustful/arbitrary-withdraw.ts",
    group: "trustful",
    role: "manager",
    network: "none",
    summary: "Withdraw from a Trustful arbitrary strategy.",
    transactional: true,
    offline: true,
    load: () => import("./trustful/arbitrary-withdraw.js"),
  },
  {
    name: "trustful:curve-init",
    file: "examples/src/trustful/curve-init.ts",
    group: "trustful",
    role: "manager",
    network: "none",
    summary: "Initialize the Trustful curve strategy.",
    transactional: true,
    offline: true,
    load: () => import("./trustful/curve-init.js"),
  },
  {
    name: "trustful:curve-borrow",
    file: "examples/src/trustful/curve-borrow.ts",
    group: "trustful",
    role: "manager",
    network: "none",
    summary: "Borrow against the Trustful curve strategy.",
    transactional: true,
    offline: true,
    load: () => import("./trustful/curve-borrow.js"),
  },
  {
    name: "trustful:curve-repay",
    file: "examples/src/trustful/curve-repay.ts",
    group: "trustful",
    role: "manager",
    network: "none",
    summary: "Repay the Trustful curve strategy.",
    transactional: true,
    offline: true,
    load: () => import("./trustful/curve-repay.js"),
  },
  {
    name: "trustful:curve-remove",
    file: "examples/src/trustful/curve-remove.ts",
    group: "trustful",
    role: "manager",
    network: "none",
    summary: "Close the Trustful curve strategy.",
    transactional: true,
    offline: true,
    load: () => import("./trustful/curve-remove.js"),
  },

  // Composition across packages
  {
    name: "composition:allocate",
    file: "examples/src/composition/allocate.ts",
    group: "composition",
    role: "manager",
    network: "none",
    summary: "Sequence builders from >1 package through the shared processor.",
    transactional: true,
    offline: true,
    load: () => import("./composition/allocate.js"),
  },
];

export function findEntry(name: string): RegistryEntry | undefined {
  return registry.find((entry) => entry.name === name);
}

export function findMeta(name: string): ExampleMeta | undefined {
  return findEntry(name);
}
