/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
  SolanaError,
  type Address,
  type ClientWithRpc,
  type GetAccountInfoApi,
  type GetMultipleAccountsApi,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  addSelfFetchFunctions,
  type SelfFetchFunctions,
} from "@solana/program-client-core";
import {
  getStrategyInitReceiptCodec,
  type StrategyInitReceipt,
  type StrategyInitReceiptArgs,
} from "../accounts/index.js";

export const VOLTR_VAULT_PROGRAM_ADDRESS =
  "vVoLTRjQmtFpiYoegx285Ze4gsLJ8ZxgFKVcuvmG1a8" as Address<"vVoLTRjQmtFpiYoegx285Ze4gsLJ8ZxgFKVcuvmG1a8">;

export enum VoltrVaultAccount {
  StrategyInitReceipt,
}

export function identifyVoltrVaultAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): VoltrVaultAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([51, 8, 192, 253, 115, 78, 112, 214]),
      ),
      0,
    )
  ) {
    return VoltrVaultAccount.StrategyInitReceipt;
  }
  throw new SolanaError(
    SOLANA_ERROR__PROGRAM_CLIENTS__FAILED_TO_IDENTIFY_ACCOUNT,
    { accountData: data, programName: "voltrVault" },
  );
}

export type VoltrVaultPlugin = { accounts: VoltrVaultPluginAccounts };

export type VoltrVaultPluginAccounts = {
  strategyInitReceipt: ReturnType<typeof getStrategyInitReceiptCodec> &
    SelfFetchFunctions<StrategyInitReceiptArgs, StrategyInitReceipt>;
};

export type VoltrVaultPluginRequirements = ClientWithRpc<
  GetAccountInfoApi & GetMultipleAccountsApi
>;

export function voltrVaultProgram() {
  return <T extends VoltrVaultPluginRequirements>(client: T) => {
    return {
      ...client,
      voltrVault: <VoltrVaultPlugin>{
        accounts: {
          strategyInitReceipt: addSelfFetchFunctions(
            client,
            getStrategyInitReceiptCodec(),
          ),
        },
      },
    };
  };
}
