/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const STRATEGY_INIT_RECEIPT_DISCRIMINATOR = new Uint8Array([
  51, 8, 192, 253, 115, 78, 112, 214,
]);

export function getStrategyInitReceiptDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    STRATEGY_INIT_RECEIPT_DISCRIMINATOR,
  );
}

export type StrategyInitReceipt = {
  discriminator: ReadonlyUint8Array;
  /** The vault associated with this strategy. */
  vault: Address;
  /** The strategy address. */
  strategy: Address;
  /** The adaptor program address. */
  adaptorProgram: Address;
  /** The position value. */
  positionValue: bigint;
  /** The last updated timestamp. */
  lastUpdatedTs: bigint;
  /** A version number (1 byte). */
  version: number;
  /** The bump for the strategy init receipt. */
  bump: number;
  /** The bump for the vault strategy auth. */
  vaultStrategyAuthBump: number;
  /** 5 bytes of padding to align future 8-byte fields on 8-byte boundaries. */
  padding0: ReadonlyUint8Array;
  /**
   * The strategy ATA amount included in the preceding accounting snapshot.
   * This reuses the first 8 bytes of the v1 reserved region.
   */
  lastAccountedStrategyAtaAmount: bigint;
  /** Reserved space for future fields. */
  reserved: ReadonlyUint8Array;
};

export type StrategyInitReceiptArgs = {
  /** The vault associated with this strategy. */
  vault: Address;
  /** The strategy address. */
  strategy: Address;
  /** The adaptor program address. */
  adaptorProgram: Address;
  /** The position value. */
  positionValue: number | bigint;
  /** The last updated timestamp. */
  lastUpdatedTs: number | bigint;
  /** A version number (1 byte). */
  version: number;
  /** The bump for the strategy init receipt. */
  bump: number;
  /** The bump for the vault strategy auth. */
  vaultStrategyAuthBump: number;
  /** 5 bytes of padding to align future 8-byte fields on 8-byte boundaries. */
  padding0: ReadonlyUint8Array;
  /**
   * The strategy ATA amount included in the preceding accounting snapshot.
   * This reuses the first 8 bytes of the v1 reserved region.
   */
  lastAccountedStrategyAtaAmount: number | bigint;
  /** Reserved space for future fields. */
  reserved: ReadonlyUint8Array;
};

/** Gets the encoder for {@link StrategyInitReceiptArgs} account data. */
export function getStrategyInitReceiptEncoder(): FixedSizeEncoder<StrategyInitReceiptArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["vault", getAddressEncoder()],
      ["strategy", getAddressEncoder()],
      ["adaptorProgram", getAddressEncoder()],
      ["positionValue", getU64Encoder()],
      ["lastUpdatedTs", getU64Encoder()],
      ["version", getU8Encoder()],
      ["bump", getU8Encoder()],
      ["vaultStrategyAuthBump", getU8Encoder()],
      ["padding0", fixEncoderSize(getBytesEncoder(), 5)],
      ["lastAccountedStrategyAtaAmount", getU64Encoder()],
      ["reserved", fixEncoderSize(getBytesEncoder(), 56)],
    ]),
    (value) => ({
      ...value,
      discriminator: STRATEGY_INIT_RECEIPT_DISCRIMINATOR,
    }),
  );
}

/** Gets the decoder for {@link StrategyInitReceipt} account data. */
export function getStrategyInitReceiptDecoder(): FixedSizeDecoder<StrategyInitReceipt> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["vault", getAddressDecoder()],
    ["strategy", getAddressDecoder()],
    ["adaptorProgram", getAddressDecoder()],
    ["positionValue", getU64Decoder()],
    ["lastUpdatedTs", getU64Decoder()],
    ["version", getU8Decoder()],
    ["bump", getU8Decoder()],
    ["vaultStrategyAuthBump", getU8Decoder()],
    ["padding0", fixDecoderSize(getBytesDecoder(), 5)],
    ["lastAccountedStrategyAtaAmount", getU64Decoder()],
    ["reserved", fixDecoderSize(getBytesDecoder(), 56)],
  ]);
}

/** Gets the codec for {@link StrategyInitReceipt} account data. */
export function getStrategyInitReceiptCodec(): FixedSizeCodec<
  StrategyInitReceiptArgs,
  StrategyInitReceipt
> {
  return combineCodec(
    getStrategyInitReceiptEncoder(),
    getStrategyInitReceiptDecoder(),
  );
}

export function decodeStrategyInitReceipt<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<StrategyInitReceipt, TAddress>;
export function decodeStrategyInitReceipt<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<StrategyInitReceipt, TAddress>;
export function decodeStrategyInitReceipt<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  | Account<StrategyInitReceipt, TAddress>
  | MaybeAccount<StrategyInitReceipt, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getStrategyInitReceiptDecoder(),
  );
}

export async function fetchStrategyInitReceipt<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<StrategyInitReceipt, TAddress>> {
  const maybeAccount = await fetchMaybeStrategyInitReceipt(
    rpc,
    address,
    config,
  );
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeStrategyInitReceipt<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<StrategyInitReceipt, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeStrategyInitReceipt(maybeAccount);
}

export async function fetchAllStrategyInitReceipt(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<StrategyInitReceipt>[]> {
  const maybeAccounts = await fetchAllMaybeStrategyInitReceipt(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeStrategyInitReceipt(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<StrategyInitReceipt>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeStrategyInitReceipt(maybeAccount),
  );
}

export function getStrategyInitReceiptSize(): number {
  return 192;
}
